# MIT License
# Copyright (c) 2024 [SNALE - French SAS Company - RCS 951 724 616]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spatialetl"
version = "0.2.0"
requires-python = ">=3.9"
authors = [
  {name = "Fabien RÉTIF", email = "fabien.retif@snale.net"},
]
description = "Extract - Transform - Load (ETL) of geospatial data, that is, digital geospatial information representing space and time-varying phenomena. This python package deals with multi-dimensional gridded data and multi-dimensional multi-point data."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]

dependencies = [
    "spatialetl-core==0.0.1",
]
packages = []

[project.urls]
Homepage = "https://lab.snale.net/produits/pyspatialetl"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/snale-net/pySpatialETL.git"

[tool.setuptools.packages.find]
exclude = ["spatialetl.providers","spatialetl.providers.*","*.tests", "*.tests.*", "tests.*", "tests", "demo"]

[project.optional-dependencies]
"gdal" = [
    "spatialetl-providers-common-gdal"
]
"grib" = [
    "spatialetl-providers-common-grib"
]
"mpi" = [
    "spatialetl-providers-common-mpi"
]
"netcdf" = [
    "spatialetl-providers-common-netcdf"
]
"ecmwf" = [
    "spatialetl-providers-ecmwf"
]
"gmt" = [
    "spatialetl-providers-gmt"
]
"hycom" = [
    "spatialetl-providers-hycom"
]
"mercator" = [
    "spatialetl-providers-mercator"
]
"meteofrance" = [
    "spatialetl-providers-meteofrance"
]
"swan" = [
    "spatialetl-providers-swan"
]
"symphonie" = [
    "spatialetl-providers-symphonie"
]
"telemac" = [
    "spatialetl-providers-telemac"
]
"ww3" = [
    "spatialetl-providers-ww3"
]
"all" = [
    "spatialetl-providers-common-gdal",
    "spatialetl-providers-common-grib",
    "spatialetl-providers-common-mpi",
    "spatialetl-providers-common-netcdf",
    "spatialetl-providers-ecmwf",
    "spatialetl-providers-gmt",
    "spatialetl-providers-hycom",
    "spatialetl-providers-mercator",
    "spatialetl-providers-meteofrance",
    "spatialetl-providers-swan",
    "spatialetl-providers-symphonie",
    "spatialetl-providers-telemac",
    "spatialetl-providers-ww3",
]

## pytest settings ##
[tool.pytest.ini_options]
# We need to make sure airflow-core sources are first in the pythonpath, because uv sync adds sources to
# pythonpath in basically random order and pytest does not understand legacy namespace packages and cannot
# use namespace packages effectively when collecting tests.
pythonpath = [
    "spatialetl-core"
]
testpaths = [
    "tests",
]
asyncio_default_fixture_loop_scope = "function"
log_cli = true
log_cli_level = "DEBUG"

[tool.uv.sources]
# These names must match the names as defined in the pyproject.toml of the workspace items,
# *not* the workspace folder paths
spatialetl = {workspace = true}
spatialetl-core = {workspace = true}
spatialetl-providers-common-gdal = {workspace = true}
spatialetl-providers-common-grib = {workspace = true}
spatialetl-providers-common-mpi = {workspace = true}
spatialetl-providers-common-netcdf = {workspace = true}
spatialetl-providers-ecmwf = {workspace = true}
spatialetl-providers-gmt = {workspace = true}
spatialetl-providers-hycom = {workspace = true}
spatialetl-providers-mercator = {workspace = true}
spatialetl-providers-meteofrance = {workspace = true}
spatialetl-providers-swan = {workspace = true}
spatialetl-providers-symphonie = {workspace = true}
spatialetl-providers-telemac = {workspace = true}
spatialetl-providers-ww3 = {workspace = true}

[tool.uv.workspace]
members = [
    ".",
    "spatialetl-core",
    "providers/common/gdal",
    "providers/common/grib",
    "providers/common/mpi",
    "providers/common/netcdf",
    "providers/ecmwf",
    "providers/gmt",
    "providers/hycom",
    "providers/mercator",
    "providers/meteofrance",
    "providers/swan",
    "providers/symphonie",
    "providers/telemac",
    "providers/ww3",
]
