name: Publish extensions distribution 📦 to Test PyPI

on:
  push:
    tags: extensions-[a-z0-9]+/[0-9]+.[0-9]+.[0-9]+rc[0-9]+

jobs:
  release-checks:
    outputs:
      extension-name: ${{ steps.check-extension.outputs.extension-name }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Find extension name"
        uses: actions-ecosystem/action-regex-match@v2
        id: extension-parser
        with:
            text: ${{ github.ref }}
            regex: '^refs\/tags\/extensions-([a-z0-9]+)\/.*$'

      - name: "Check prodiver"
        if: ${{ (steps.extension-parser.outputs.match != '') && (hashFiles(format('spatialetl/extensions/{0}/', steps.extensions-parser.outputs.group1)) != '' ) }}
        id: check-extension
        run: echo extension-name=${{ steps.extensions-parser.outputs.group1 }} >> $GITHUB_OUTPUT

  publish-to-pypi:
    name: Publish release to Test PyPI
    runs-on: ubuntu-latest
    needs:
      - release-checks
    if: needs.release-checks.outputs.extension-name != ''
    environment:
      name: testpypi
      url: https://test.pypi.org/p/spatialetl-${{ needs.release-checks.outputs.extension-name }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Build package
        run: |
          python -m build
      - name: "Publishing ${{ needs.release-checks.outputs.extension-name }} distribution 📦 to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          attestations: true